### ISSUE TITLE
Awesome - but I miss one single option

### ISSUE THREAD

**Issue by finefin** [MrSamSeen/ComfyUI_SSStereoscope#3]
Thank you so much for this small and efficient node, it works like a charm and is very fast!
But I am missing the option to **swap the output images** to allow parallel _and_ cross-eye view.

**Comment by MrSamSeen** [comment]
Hi,
Thank you so much for your feedback, I'll try to push an update today.

**Comment by finefin** [comment]
awesome, thank you!
However, the correct wording would be "parallel" (this is what you had before) and "cross-eye" (the new mode).
